# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLDBaseRepository' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MLDBaseRepository
pod 'pop'
pod 'YYKit'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'IQKeyboardManager'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'XHToast'
pod 'RDVTabBarController'
pod 'TYPagerController'
pod 'SDCycleScrollView', '~> 1.65'
pod 'Wonderful'
end
